# Generated by Django 5.2.17 on 2026-09-05 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters', models.BooleanField(default=True)),
                ('rooms', models.BooleanField(default=True)),
                ('worlds', models.BooleanField(default=True)),
                ('scenes', models.BooleanField(default=True)),
                ('photos', models.BooleanField(default=True)),
                ('delete_projects', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
