# Generated by Django 5.2.17 on 2026-09-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_useraccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAccess',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('https_origins', models.JSONField(default=list)),
            ],
        ),
    ]
