"""Generate the synchronous JS catalog from the shared validated JSON source."""
import json
from pathlib import Path
root = Path(__file__).resolve().parent.parent
catalog = json.loads((root / 'static/studio/avatar-catalog.json').read_text())
(root / 'static/studio/avatar-catalog.js').write_text(
    '// Generated by scripts/sync_assets.py; edit avatar-catalog.json.\n'
    'export const catalog=' + json.dumps(catalog, ensure_ascii=False) + ';\n'
)
